### ISSUE TITLE
Streamlining new module generation

### ISSUE THREAD

**Issue by ojarvin** [TheSystemDevelopmentKit/thesdk_helpers#1]
Some proposed changes to the template generated by running ./shell/initentity.sh:

1. "@inverter" module should be named after the given module name
2. The template should include a .gitignore file with entries for 

`*.swp`
`*~`
`Makefile`
`<modulename>/__pycache__/`
`*.eps`
`*.pdf`

3. The module name in the remote could be set automatically (...../modulename.git) instead of inverter

**Comment by ojarvin** [comment]
Ping @mkosunen

**Comment by mkosunen** [comment]
Commit edf3fbe a18de20 adds .gitignore to inverter template.  Updated to thesdk_template v1.3_RC.

**Comment by mkosunen** [comment]
Part 1. closed with commit  0a6798243e46932d101c5d. thesdk_template updated accordngly.
